apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce-app
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ecomdb


---
kind: PersistentVolume
apiVersion: v1
metadata:
   name: postgres-volume 
   namespace: ecommerce-app
spec:
  storageClassName: postgres-pv 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
   path: /data/postgresql

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-volume-claim 
   namespace: ecommerce-app
spec:
   storageClassName: postgres-pv 
   accessModes: 
     - ReadWriteMany
   resources:
    requests:
     storage: 1Gi


---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: postgres-deployment
   namespace: ecommerce-app
spec:
   replicas: 1
   selector:
    matchLabels:
     app: postgres
   template:
    metadata:
     labels:
      app: postgres
    spec:
     containers:
     - name: postgres
       image: postgres:latest
       ports:
       - containerPort: 5432
       envFrom:
        - secretRef:
            name: postgres-secret
       volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: postgresdata
     volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-volume-claim

---

kind: Service
apiVersion: v1
metadata:
   name: ecommerce-postgres
   namespace: ecommerce-app
spec: 

   selector:
     app: postgres
   ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432
